services:
  veritabani:
    image: postgres:15-alpine
    container_name: kavrulmus_postgres
    restart: always
    environment:
      POSTGRES_USER: patron
      POSTGRES_PASSWORD: Furkan20052005
      POSTGRES_DB: kavrulmus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: